### ISSUE TITLE
Gradle not available in Android Images

### ISSUE THREAD

**Issue by gregberns** [circleci/circleci-images#118]
I have a poc Cordova project I'm trying to get running with the v2 script, but Gradle doesn't seem to be available as a global on the command line. It looks like the OpenJava image should be installing it.

I'm new to Circle's v2 and Cordova, there seems to be an issue, but maybe I'm just missing something. 

I've tried with both the node and non-node Android images (same result).

Is there something special I have to do to call Gradle?

Any thoughts?

Error:
```
#!/bin/bash -eo pipefail
gradle -v
/bin/bash: gradle: command not found
Exited with code 127
```

Script:
```
version: 2
jobs:
  #build-and-test:
  build:
    # macos:
    #   xcode: "9.0"
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-node8-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install Node Dependencies
          command: gradle -v
```
