### ISSUE TITLE
Android emulator out of date

### ISSUE THREAD

**Issue by gusterwoei-veltra** [circleci/circleci-images#140]
Trying to launch an Android emulator but received the following error:
```
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"
```

Then it will get timeout after 10 minutes.

Here's my config.yml:
```
version: 2
jobs:
  build:
    working_directory: ~/calabash-test
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: echo $ANDROID_HOME
      - run: 
          name: Remove local.properties from the project
          command: rm local.properties

      - run:
          name: Setup emulator
          command: sdkmanager --update && sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n device1 -k "system-images;android-25;google_apis;armeabi-v7a"
      - run:
          name: Starting Android Emulator:
          command: emulator -avd device1 -no-audio -no-window
```

Any idea?
