### ISSUE TITLE
Include `pipenv` in the python images?

### ISSUE THREAD

**Issue by glenjamin** [circleci/circleci-images#168]
See https://docs.pipenv.org/

pipenv seems to be gaining traction as a standard way to create and manage virtualenvs for python projects.

It would be great to bake this into the circleci build containers, and possibly include some documentation samples of which directories to cache to get the best results.

I'm figuring out the cache dirs myself at the moment, will post an update on here when I identify the right paths.

**Comment by ryanwohara** [comment]
Done!

**Comment by glenjamin** [comment]
Brilliant, thanks!

**Comment by glenjamin** [comment]
This is what I ended up with for caching config:

```
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
```

How often do the docker image builds run?
