### ISSUE TITLE
npm ci not found in circleci/node:latest and circleci/node:10.1

### ISSUE THREAD

**Issue by DrSensor** [circleci/circleci-images#192]
```yml
  docker:
    - image: circleci/node:10.1
# or
    - image: circleci/node:latest
  steps:
    - checkout
    - run: npm ci
```

```bash
#!/bin/bash -eo pipefail
npm ci

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/circleci/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.6.0 /usr/local/lib/node_modules/npm

Did you mean one of these?
    c
    i
Exited with code 1
```
