### ISSUE TITLE
Problem with latest postgis image (circleci/postgres:9.6-postgis)

### ISSUE THREAD

**Issue by dlancer** [circleci/circleci-images#211]
Our ci config:
```
docker:
  - image: circleci/postgres:9.6-postgis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
```

Error:
```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh
/docker-entrypoint-initdb.d/postgis.sh: 9: /docker-entrypoint-initdb.d/postgis.sh: Bad substitution
LOG:  received SIGHUP, reloading configuration files
LOG:  parameter "listen_addresses" cannot be changed without restarting the server
LOG:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors; unaffected changes were applied
```
