### ISSUE TITLE
Old version of awscli makes it impossible to use AWS APIs

### ISSUE THREAD

**Issue by fedecarg** [circleci/circleci-images#233]
I spent a lot of time trying to upgrade `awscli` to the latest version. It doesn't matter what I add to `config.yml`, the `node:9` image always shows an old version of `awscli`:

```
$ aws --version
aws-cli/1.11.165 Python/2.7.6 Linux/4.4.0-96-generic botocore/1.7.23
```

I tried upgrading using `pip`:

```
default_node_image: &default_node_image
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
      - run: sudo pip install -q awscli --upgrade
```

But that didn't work either, CircleCI still shows:
```
$ aws --version
aws-cli/1.11.165 Python/2.7.6 Linux/4.4.0-96-generic botocore/1.7.23
```

It's impossible to upgrade to `aws-cli/1.15.20` in order to take advantage of the latest AWS services.
