### ISSUE TITLE
Licenses in circleci/android:api-27-alpha & circleci/android:api-27-node8-alpha

### ISSUE THREAD

**Issue by tkhduracell** [circleci/circleci-images#249]
Hi I have a problem with the licenses in the lastest docker images. 

```yaml
version: 2.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-node8-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew check build assembleAndroidTest

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build:
   jobs:
     - build
```

*Output*

```
...
Download https://jcenter.bintray.com/com/sun/istack/istack-commons-runtime/2.21/istack-commons-runtime-2.21.jar
Download https://jcenter.bintray.com/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
Download https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
Checking the license for package Android SDK Build-Tools 27.0.3 in /home/circleci/code/licenses
Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.
Checking the license for package Android SDK Platform 27 in /home/circleci/code/licenses
Warning: License for package Android SDK Platform 27 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-27 Android SDK Platform 27
     build-tools;27.0.3 Android SDK Build-Tools 27.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /home/circleci/code

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 16s
Error: Exited with code 1
Step failed
```

I've tried adding steps like
```
      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies && true
            echo "Y" | sdkmanager "build-tools;27.0.3"
            echo "Y" | sdkmanager "platforms;android-27"
            yes | sdkmanager --licenses && sdkmanager --update
```
However, it seems like the licenses aren't activated anyway.
