### ISSUE TITLE
Unable to run `docker push` with docker client `19.03.09` installed on latest convenience images

### ISSUE THREAD

**Issue by lokst** [circleci/circleci-images#487]
## Issue

The latest convenience images have docker client `19.03.09` installed on them.

There appears to be an issue with this particular version (see issue we filed here: https://github.com/docker/cli/issues/2533), which causes many docker commands like `docker push` to fail when used with certain versions of Docker daemon e.g. `18.09.3`, with an error message like: `Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39`

### How to reproduce

```
version: 2.1

executors:
  docker-190309:
    docker:
      - image: circleci/golang:latest
  docker-190308:
    docker:
      - image: ccitest/golang@sha256:095ace63d699ff06e5d22677585f0b6ece9e239586659ad4c3de8f6a18ebb3b2

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: 
          name: Build and push image
          command: |
            docker info
            docker version
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t $DOCKER_USER/test-image:$CIRCLE_SHA1 .
            docker push $DOCKER_USER/test-image:$CIRCLE_SHA1
            
workflows:
  build-and-deploy:
    jobs:
      - build:
          name: build-latest
          executor: docker-190309
      - build:
          name: build-190308
          executor: docker-190308
```
