### ISSUE TITLE
awscli and other deployment tools request

### ISSUE THREAD

**Issue by shawnmclean** [circleci/circleci-images#53]
I saw in the doc that you're awaiting signaling from users before adding deploy tools like `awscli` to the container. It would be great for these deploy tools to come packaged with the build containers as it would prevent us from building our own containers just to add these tools, seeing as most, if not everything else is provided for us in those language containers.

**Comment by l85m** [comment]
Until AWS CLI is included adding these steps to the config.yml will let you continue to use circleci images in builds, which seems a bit faster than building your own:

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/my-app
    steps:
      - checkout

      # Run local steps before AWS is required so if they 
      # fail you don't waste build time installing AWS CLI

      # Install AWS CLI
      # - include aws cli ci docker: 
      #     https://github.com/circleci/circleci-images/issues/53
      # - use global install for aws and pip instead of --user:
      #     https://discuss.circleci.com/t/how-to-add-a-path-to-path-in-circle-2-0/11554
      - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
      - run: sudo pip install -q awscli --upgrade

      # Do stuff with AWS CLI
```

**Comment by ryanwohara** [comment]
The problem with installing awscli on every container is the large Python dependencies. It's definitely worth consideration, though.

**Comment by watsonarw** [comment]
Alternatively, would it be possible to get individual images for the deployment tools that we can use in the same way as the language containers?

We can use the workspace to share deployable artefacts between workflow jobs, and separate the concerns of building/testing and deploying.

Something like:

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/my-app
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist
  deploy:
    docker:
      # Image with awscli
      - image: circleci/awscli:latest
    working_directory: ~/my-app
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Deploy
        command: scripts/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
```

**Comment by klebba** [comment]
I agree that this would be ideal: `-image: circleci/awscli:latest`

**Comment by felicianotech** [comment]
Work in Progress (WIP) 2nd party image here: https://github.com/cibuilds/aws

**Comment by ryanwohara** [comment]
We don't want to install the large Python dependencies in all the language images. There are some third-party images, like Ricardo's, that will do the trick.

**Comment by cam-fulcrum** [comment]
Could you not have a separate `aws-cli` image? If inside our builds all we're wanting to do is do tasks via the aws-cli it means we have to build our own

**Comment by devourment77** [comment]
Agreed it would be cool to have things like circleci/node-awscli:9.11 w/o having to maintain our own custom image.  It would save  ~ 20 seconds off our builds.

**Comment by bitblit** [comment]
Its a pretty huge breaker to a lot of deployment scripts - the lack of official support for something this is a clear break of backwards compatibility added 8 months to when I would have moved my stuff to version 2.0.

**Comment by merwok** [comment]
One thing I don’t understand in this thread: with workflows, we are free to split the work in jobs with their own docker image and environment, so what is the need to add awscli to every language image?

I have projects with jobs that that use a python or nodejs image to run tests or build a package, and other jobs use images with awscli or even rsync to deploy in various ways.

**Comment by Tensho** [comment]
@merwok AFAIK, you need a combination of docker cli/docker-compose and awscli because of the remote docker execution environment. CircleCI doesn't guarantee that you get the same remote docker engine across jobs (even if you pay for layer cache feature). That means you are not able to **build image with docker** in **job A** (from circleci/buildpack-deps) and then **push image to AWS ECR** in **job B** (from your custom primary image), because they may refer to different docker engines and their image regestries. At least that was last time I checked this 6 months ago, maybe something has been changed from that time. I'd be happy if someone from @circleci correct me if I'm wrong.

**Comment by merwok** [comment]
Indeed, in the projects I’m looking at there is a job with nodejs image to install dependencies and build, and another job uses a python image (with docker and awscli) to run steps that build then push the docker image.

**Comment by Tensho** [comment]
@merwok You share not images from local registry, but `awscli` within CircleCI workspaces, isn't it? 🤔  From that point of view it makes sense. **Job A** builds from `circleci/python` image `awscli`, then passes AWS CLI within the workspace persistence feature to the **job B**, which runs docker image build and push to ECR from `circleci/buildpack-deps` in turn. Is it correct?

**Comment by merwok** [comment]
Not sure what you mean with the question «you share not images».

I’m building a docker image and pushing it to ECR or Docker Hub, in two steps of the same job.

**Comment by Tensho** [comment]
@ryanwohara, Are you plan to create official pre-build image with `awscli` (kinda `circleci/awscli:latest`)? AWS ECR is one of the primary used registries in the wood, not only my company requires it. Of course we all move with our custome primary images, but I find it'd be nice to have it out of the box.

**Comment by merwok** [comment]
I was agreeing with you that the same job needs to build and push the image.
In my projects we think it’s fine.

**Comment by fedecarg** [comment]
I can't believe the amount of time I spent trying to upgrade `awscli` to the latest version. It doesn't matter what I add to `config.yml`, the `node:9` image always shows an old version of `awscli`:

```
$ aws --version
aws-cli/1.11.165 Python/2.7.6 Linux/4.4.0-96-generic botocore/1.7.23
```

I tried upgrading using `pip`:

```
default_node_image: &default_node_image
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
      - run: sudo pip install -q awscli --upgrade
```

But that didn't work either, CircleCI still shows:
```
$ aws --version
aws-cli/1.11.165 Python/2.7.6 Linux/4.4.0-96-generic botocore/1.7.23
```

It's impossible to upgrade to `aws-cli/1.15.20` in order to take advantage of the latest AWS services.

I'm blocked.

**Comment by fedecarg** [comment]
I spent a lot of time trying to upgrade `awscli` to the latest version. It doesn't matter what I add to `config.yml`, the `node:9` image always shows an old version of `awscli`:

```
$ aws --version
aws-cli/1.11.165 Python/2.7.6 Linux/4.4.0-96-generic botocore/1.7.23
```

I tried upgrading using `pip`:

```
default_node_image: &default_node_image
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
      - run: sudo pip install -q awscli --upgrade
```

But that didn't work either, CircleCI still shows:
```
$ aws --version
aws-cli/1.11.165 Python/2.7.6 Linux/4.4.0-96-generic botocore/1.7.23
```

It's impossible to upgrade to `aws-cli/1.15.20` in order to take advantage of the latest AWS services.
