### ISSUE TITLE
Python unable to detect lzma in Ubuntu images

### ISSUE THREAD

**Issue by mackrorysd** [circleci/circleci-images#533]
I hit an error similar to the following in the Ubuntu 16.04 and Ubuntu 20.04 images: https://github.com/pandas-dev/pandas/issues/27532. I believe this problem occurs because Python is installed prior to the installation of the xz and liblzma-dev packages. The workaround is to run `pyenv uninstall -f 3.6.10` and `pyenv install 3.6.10` (or whatever the Python version is in the image) in my CI jobs. Would be nice if the ordering could be fixed without causing other problems.

To reproduce the problem:

```
pyenv global 3.6.10
python3 -m venv /tmp/no-lzma
export PATH=/tmp/no-lzma/bin:${PATH}
pip install torchvision==0.8.1
python -c "import torchvision"
```

To demonstrate the workaround:

```
pyenv uninstall -f 3.6.10
pyenv install 3.6.10
pyenv global 3.6.10
python3 -m venv /tmp/no-lzma
export PATH=/tmp/no-lzma/bin:${PATH}
pip install torchvision==0.8.1
python -c "import torchvision"
```

3.6.10 is the Python version in the Ubuntu 16.04 image. I had the same experience with Python 3.8.5 in an Ubuntu 20.04 image.

**Comment by ryanwohara** [comment]
> I hit an error similar to the following in the Ubuntu 16.04 and Ubuntu 20.04 images

Which images are you referring to? It looks like the Python images are based on Debian.
Are you talking about the machine images? https://circleci.com/docs/2.0/configuration-reference/#available-machine-images

**Comment by mackrorysd** [comment]
Yes, sorry, machine images. I've specifically done this with ubuntu-2004:202010-01 and ubuntu-1604:202004-01.

**Comment by dsayling** [comment]
fyi, this issue is now resolved in the latest images `ubuntu-2004:202101-01`

You can verify with this config

```
version: 2.1

jobs:
  sample:
    machine:
      image: ubuntu-2004:202010-01 
    steps:
      - run:
          name: load latest
          command: |
            python3 -c 'import lzma; print(dir(lzma))'
  sample-latest:
    machine:
      image: ubuntu-2004:202101-01 
    steps:
      - run:
          name: load latest
          command: |
            python3 -c 'import lzma; print(dir(lzma))'

workflows:
  main:
    jobs:
      - sample  # this one fails
      - sample-latest  # this one passess
 ```
